spring:
  profiles:
    active: local
  application:
    name: worklangcorrector
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: none    # 자동 테이블 생성/갱신 (옵션: none, update, validate, create, create-drop)
    show-sql: true      # 실행되는 SQL 로그 출력
    properties:
      hibernate.format_sql: true  # SQL을 보기 좋게 출력
      hibernate.use_sql_comments: true # SQL 주석 활성화
  sql:
    init:
      mode: always
      schema-locations: classpath:h2/schema.sql
      data-locations: classpath:h2/data.sql
logging:
  level:
    org.springframework.web:
      DEBUG